import type { Category, City, Experience } from './types'

export const TRIP_START = '2026-03-14'
export const TRIP_END = '2026-03-21'
export const TRIP_DAYS = [
  '2026-03-14',
  '2026-03-15',
  '2026-03-16',
  '2026-03-17',
  '2026-03-18',
  '2026-03-19',
  '2026-03-20',
  '2026-03-21',
]

export const ALL_INTERESTS: Category[] = [
  'Food',
  'Nightlife',
  'Art',
  'Anime',
  'Music',
  'Nature',
  'Shopping',
  'Festivals',
  'Wellness',
  'Traditional',
]

export const ALL_CITIES: City[] = ['Tokyo', 'Kyoto', 'Osaka']

export const CITY_IMAGE: Record<City, string> = {
  Tokyo: '/poster/shibuya-sky.jpg',
  Kyoto: '/poster/fushimi-inari.jpg',
  Osaka: '/poster/dotonbori.jpg',
}

const p = (slug: string) => `/poster/${slug}.jpg`

export const EXPERIENCES: Experience[] = [
  {
    id: 'ameyoko',
    title: 'Ameyoko Night Market Food Crawl',
    city: 'Tokyo',
    neighborhood: 'Ueno, Taitō',
    date: '2026-03-14',
    startTime: '19:00',
    durationMin: 150,
    description:
      'Thread through the lantern-lit stalls under the train tracks, tasting grilled skewers, fresh oysters, and steaming taiyaki as you go. A local guide reads the crowd and orders whatever is best that night.',
    tags: ['Food', 'Nightlife'],
    matchReason: 'Because you like street food',
    host: { name: 'Rei Nakamura', avatarUrl: '', verified: true },
    saveCount: 1284,
    shareCount: 212,
    videoUrl: null,
    posterUrl: p('ameyoko'),
    lat: 35.7089,
    lng: 139.7741,
    ageAccess: 'All ages',
  },
  {
    id: 'golden-gai',
    title: 'Golden Gai Jazz Bar Hop',
    city: 'Tokyo',
    neighborhood: 'Shinjuku',
    date: '2026-03-15',
    startTime: '20:30',
    durationMin: 180,
    description:
      'Six-seat bars stacked along impossibly narrow lanes, each with its own record collection and house rule. We visit three, from a bebop den to a vinyl-only listening room, with the bartenders as your soundtrack.',
    tags: ['Music', 'Nightlife'],
    matchReason: 'Because you mentioned tiny jazz bars',
    host: { name: 'Haruki Sato', avatarUrl: '', verified: true },
    saveCount: 976,
    shareCount: 188,
    videoUrl: null,
    posterUrl: p('golden-gai'),
    lat: 35.6938,
    lng: 139.7048,
    ageAccess: '20+ (ID required)',
  },
  {
    id: 'fushimi-inari',
    title: 'Fushimi Inari Sunrise Hike',
    city: 'Kyoto',
    neighborhood: 'Fushimi',
    date: '2026-03-16',
    startTime: '06:00',
    durationMin: 165,
    description:
      'Climb the thousand vermilion torii before the tour buses arrive. At dawn the mountain is yours: fox shrines in the mist, the city waking below, and a tea house near the summit for a quiet finish.',
    tags: ['Nature', 'Traditional'],
    matchReason: "Because you'd rather avoid crowds",
    host: { name: 'Aiko Tanaka', avatarUrl: '', verified: true },
    saveCount: 2140,
    shareCount: 401,
    videoUrl: null,
    posterUrl: p('fushimi-inari'),
    lat: 34.9671,
    lng: 135.7727,
    ageAccess: 'All ages',
  },
  {
    id: 'nakano',
    title: 'Nakano Broadway Vintage Anime Hunt',
    city: 'Tokyo',
    neighborhood: 'Nakano',
    date: '2026-03-15',
    startTime: '13:00',
    durationMin: 120,
    description:
      'Four floors of cel art, out-of-print figures, and Showa-era manga. A collector guide helps you find the real finds and haggle for the grail sitting in a glass case since 1998.',
    tags: ['Anime', 'Shopping'],
    matchReason: 'Because you like vintage shops',
    host: { name: 'Kenji Mori', avatarUrl: '', verified: false },
    saveCount: 654,
    shareCount: 97,
    videoUrl: null,
    posterUrl: p('nakano'),
    lat: 35.7076,
    lng: 139.6657,
    ageAccess: 'All ages',
  },
  {
    id: 'dotonbori',
    title: 'Dotonbori Kushikatsu Counter Tour',
    city: 'Osaka',
    neighborhood: 'Namba',
    date: '2026-03-18',
    startTime: '19:30',
    durationMin: 135,
    description:
      'Neon on the canal, sauce you never double-dip, and counters where regulars have their own seats. We eat our way from crab to skewered everything, standing shoulder to shoulder with Osaka.',
    tags: ['Food'],
    matchReason: 'Because you like street food',
    host: { name: 'Yuna Ishikawa', avatarUrl: '', verified: true },
    saveCount: 1533,
    shareCount: 274,
    videoUrl: null,
    posterUrl: p('dotonbori'),
    lat: 34.6687,
    lng: 135.5013,
    ageAccess: 'All ages',
  },
  {
    id: 'kiyomizu',
    title: 'Kiyomizu Morning Tea Ceremony',
    city: 'Kyoto',
    neighborhood: 'Higashiyama',
    date: '2026-03-17',
    startTime: '08:00',
    durationMin: 90,
    description:
      'A tea master hosts a quiet matcha ceremony in a machiya townhouse before the district fills. Learn the fold, the turn, the pause, then step out onto the slopes toward the temple gate.',
    tags: ['Traditional', 'Wellness'],
    matchReason: 'Because you chose Traditional',
    host: { name: 'Michiko Abe', avatarUrl: '', verified: true },
    saveCount: 812,
    shareCount: 143,
    videoUrl: null,
    posterUrl: p('kiyomizu'),
    lat: 34.9948,
    lng: 135.785,
    ageAccess: 'All ages',
  },
  {
    id: 'teamlab',
    title: 'teamLab Planets Light Immersion',
    city: 'Tokyo',
    neighborhood: 'Toyosu, Kōtō',
    date: '2026-03-14',
    startTime: '15:00',
    durationMin: 120,
    description:
      'Wade barefoot through water rooms that scatter koi into blossoms, then lie beneath a ceiling of falling light. A digital art body that changes with every person who moves through it.',
    tags: ['Art'],
    matchReason: 'Because you chose Art',
    host: { name: 'Sora Fujimoto', avatarUrl: '', verified: true },
    saveCount: 1890,
    shareCount: 356,
    videoUrl: null,
    posterUrl: p('teamlab'),
    lat: 35.6493,
    lng: 139.7906,
    ageAccess: 'All ages',
  },
  {
    id: 'shimokita',
    title: 'Shimokitazawa Record & Thrift Loop',
    city: 'Tokyo',
    neighborhood: 'Shimokitazawa',
    date: '2026-03-16',
    startTime: '14:00',
    durationMin: 150,
    description:
      'The neighborhood that never grew up: crate-dig for city pop, try on 80s denim, and end at a cramped coffee stand that roasts in the window. Curated stops, plenty of room to wander off.',
    tags: ['Music', 'Shopping'],
    matchReason: 'Because you like vintage shops',
    host: { name: 'Nao Kimura', avatarUrl: '', verified: false },
    saveCount: 743,
    shareCount: 121,
    videoUrl: null,
    posterUrl: p('shimokita'),
    lat: 35.6613,
    lng: 139.6681,
    ageAccess: 'All ages',
  },
  {
    id: 'tsukiji',
    title: 'Tsukiji Outer Market Breakfast',
    city: 'Tokyo',
    neighborhood: 'Tsukiji, Chūō',
    date: '2026-03-17',
    startTime: '07:30',
    durationMin: 120,
    description:
      'Tamago on a stick, uni straight from the case, and a bowl of the morning catch while the market shouts around you. We start early, when the good stalls still have their first trays out.',
    tags: ['Food'],
    matchReason: 'Because you like street food',
    host: { name: 'Rei Nakamura', avatarUrl: '', verified: true },
    saveCount: 1367,
    shareCount: 233,
    videoUrl: null,
    posterUrl: p('tsukiji'),
    lat: 35.6654,
    lng: 139.7707,
    ageAccess: 'All ages',
  },
  {
    id: 'arashiyama',
    title: 'Arashiyama Bamboo Grove Dawn Walk',
    city: 'Kyoto',
    neighborhood: 'Arashiyama',
    date: '2026-03-18',
    startTime: '06:30',
    durationMin: 105,
    description:
      'The grove breathes differently at first light. Walk the green corridor in near silence, cross to the moss temple garden, and watch the Hozu river steam before the day begins.',
    tags: ['Nature'],
    matchReason: "Because you'd rather avoid crowds",
    host: { name: 'Aiko Tanaka', avatarUrl: '', verified: true },
    saveCount: 1620,
    shareCount: 298,
    videoUrl: null,
    posterUrl: p('arashiyama'),
    lat: 35.0176,
    lng: 135.6716,
    ageAccess: 'All ages',
  },
  {
    id: 'gion',
    title: 'Gion Geisha District Evening Stroll',
    city: 'Kyoto',
    neighborhood: 'Gion, Higashiyama',
    date: '2026-03-17',
    startTime: '18:00',
    durationMin: 90,
    description:
      'Lantern light on wooden facades, the click of geta on stone, and the chance of a geiko slipping between teahouses. A historian walks you through the etiquette and the stories behind the doors.',
    tags: ['Traditional', 'Art'],
    matchReason: 'Because you chose Traditional',
    host: { name: 'Michiko Abe', avatarUrl: '', verified: true },
    saveCount: 1105,
    shareCount: 176,
    videoUrl: null,
    posterUrl: p('gion'),
    lat: 35.0037,
    lng: 135.7788,
    ageAccess: 'All ages',
  },
  {
    id: 'nishiki',
    title: 'Nishiki Market Tasting Walk',
    city: 'Kyoto',
    neighborhood: 'Nakagyō',
    date: '2026-03-16',
    startTime: '11:00',
    durationMin: 120,
    description:
      "Kyoto's kitchen, five blocks of pickles, tofu doughnuts, and knives ground by the same family for generations. We taste widely and learn what the locals actually take home.",
    tags: ['Food', 'Traditional'],
    matchReason: 'Because you like street food',
    host: { name: 'Yuna Ishikawa', avatarUrl: '', verified: false },
    saveCount: 934,
    shareCount: 158,
    videoUrl: null,
    posterUrl: p('nishiki'),
    lat: 35.0051,
    lng: 135.7649,
    ageAccess: 'All ages',
  },
  {
    id: 'shibuya-sky',
    title: 'Shibuya Sky Sunset Deck',
    city: 'Tokyo',
    neighborhood: 'Shibuya',
    date: '2026-03-15',
    startTime: '17:15',
    durationMin: 75,
    description:
      'Ride to the open-air roof 230 meters up and watch the scramble shrink to a heartbeat as the city switches on. Timed for golden hour, with the best corner held for our group.',
    tags: ['Nature'],
    matchReason: "Because you'd rather avoid crowds",
    host: { name: 'Sora Fujimoto', avatarUrl: '', verified: true },
    saveCount: 1755,
    shareCount: 312,
    videoUrl: null,
    posterUrl: p('shibuya-sky'),
    lat: 35.6581,
    lng: 139.7017,
    ageAccess: 'All ages',
  },
  {
    id: 'akihabara',
    title: 'Akihabara Retro Arcade Crawl',
    city: 'Tokyo',
    neighborhood: 'Akihabara, Chiyoda',
    date: '2026-03-14',
    startTime: '21:00',
    durationMin: 120,
    description:
      'Multi-floor arcades still running cabinets from the 90s, rhythm games at midnight, and a claw-machine floor that will take your money and your dignity. A high-score guide shows you the real rooms.',
    tags: ['Anime', 'Nightlife'],
    matchReason: 'Because you chose Anime',
    host: { name: 'Kenji Mori', avatarUrl: '', verified: false },
    saveCount: 688,
    shareCount: 104,
    videoUrl: null,
    posterUrl: p('akihabara'),
    lat: 35.7022,
    lng: 139.7745,
    ageAccess: 'All ages',
  },
  {
    id: 'sumiyoshi',
    title: 'Sumiyoshi Spring Festival',
    city: 'Osaka',
    neighborhood: 'Sumiyoshi',
    date: '2026-03-19',
    startTime: '16:00',
    durationMin: 180,
    description:
      'Drum processions, food stalls the length of the approach, and the arched Taiko bridge lit against the shrine. We join the crowd for the evening rites, then find a quiet spot for festival sweets.',
    tags: ['Festivals', 'Traditional'],
    matchReason: 'Because you chose Festivals',
    host: { name: 'Daichi Yamamoto', avatarUrl: '', verified: true },
    saveCount: 521,
    shareCount: 88,
    videoUrl: null,
    posterUrl: p('sumiyoshi'),
    lat: 34.6126,
    lng: 135.4933,
    ageAccess: 'All ages',
  },
  {
    id: 'umeda-sky',
    title: 'Umeda Sky Floating Garden',
    city: 'Osaka',
    neighborhood: 'Kita',
    date: '2026-03-18',
    startTime: '17:00',
    durationMin: 90,
    description:
      'Two towers joined by a rooftop ring open to the wind. Ride the tunnel escalator across the gap and reach the observatory as the Yodo river turns to copper below.',
    tags: ['Nature'],
    matchReason: "Because you'd rather avoid crowds",
    host: { name: 'Daichi Yamamoto', avatarUrl: '', verified: false },
    saveCount: 842,
    shareCount: 131,
    videoUrl: null,
    posterUrl: p('umeda-sky'),
    lat: 34.7052,
    lng: 135.4903,
    ageAccess: 'All ages',
  },
  {
    id: 'kurama-onsen',
    title: 'Kurama Onsen Forest Bath',
    city: 'Kyoto',
    neighborhood: 'Kurama',
    date: '2026-03-19',
    startTime: '10:00',
    durationMin: 210,
    description:
      'A mountain rail to a cedar valley, a walk past the temple, then an open-air bath looking straight into the forest. Bring nothing, think about less. A slow morning by design.',
    tags: ['Wellness', 'Nature'],
    matchReason: 'Because you chose Wellness',
    host: { name: 'Aiko Tanaka', avatarUrl: '', verified: true },
    saveCount: 1092,
    shareCount: 167,
    videoUrl: null,
    posterUrl: p('kurama-onsen'),
    lat: 35.1197,
    lng: 135.7699,
    ageAccess: 'All ages',
  },
  {
    id: 'mori-museum',
    title: 'Mori Art Museum Late Night',
    city: 'Tokyo',
    neighborhood: 'Roppongi, Minato',
    date: '2026-03-16',
    startTime: '20:00',
    durationMin: 120,
    description:
      'Contemporary work on the 53rd floor, open long after other museums close, paired with a city view that is its own installation. A curator gives context on the current show, then leaves you to it.',
    tags: ['Art'],
    matchReason: 'Because you chose Art',
    host: { name: 'Sora Fujimoto', avatarUrl: '', verified: true },
    saveCount: 967,
    shareCount: 149,
    videoUrl: null,
    posterUrl: p('mori-museum'),
    lat: 35.6606,
    lng: 139.7298,
    ageAccess: 'All ages',
  },
  {
    id: 'namba-jazz',
    title: 'Namba Underground Jazz Session',
    city: 'Osaka',
    neighborhood: 'Namba',
    date: '2026-03-18',
    startTime: '21:30',
    durationMin: 120,
    description:
      'Down a stairwell behind a ramen shop, a basement room with a grand piano and a house trio that takes requests after midnight. Low ceiling, high standard, no phones on the tables.',
    tags: ['Music', 'Nightlife'],
    matchReason: 'Because you mentioned tiny jazz bars',
    host: { name: 'Haruki Sato', avatarUrl: '', verified: true },
    saveCount: 604,
    shareCount: 92,
    videoUrl: null,
    posterUrl: p('namba-jazz'),
    lat: 34.6659,
    lng: 135.5028,
    ageAccess: '20+ (ID required)',
  },
  {
    id: 'pontocho',
    title: 'Pontochō Alley Kaiseki Evening',
    city: 'Kyoto',
    neighborhood: 'Nakagyō',
    date: '2026-03-17',
    startTime: '19:00',
    durationMin: 150,
    description:
      'A single lantern-lit alley along the river, wooden balconies overhead, and a multi-course kaiseki that reads the season plate by plate. We hold a riverside seat as the light goes down.',
    tags: ['Food', 'Traditional'],
    matchReason: 'Because you chose Traditional',
    host: { name: 'Michiko Abe', avatarUrl: '', verified: true },
    saveCount: 1188,
    shareCount: 201,
    videoUrl: null,
    posterUrl: p('pontocho'),
    lat: 35.0045,
    lng: 135.7708,
    ageAccess: 'All ages',
  },
  {
    id: 'koenji',
    title: 'Kōenji Vintage Kimono Market',
    city: 'Tokyo',
    neighborhood: 'Kōenji, Suginami',
    date: '2026-03-20',
    startTime: '12:00',
    durationMin: 120,
    description:
      'Racks of antique silk, haori by the armful, and dealers who know the province a pattern came from. A textile guide helps you tell the 1950s from the 1920s and wrap it to wear out.',
    tags: ['Shopping', 'Traditional'],
    matchReason: 'Because you like vintage shops',
    host: { name: 'Nao Kimura', avatarUrl: '', verified: false },
    saveCount: 577,
    shareCount: 84,
    videoUrl: null,
    posterUrl: p('koenji'),
    lat: 35.7051,
    lng: 139.6497,
    ageAccess: 'All ages',
  },
  {
    id: 'osaka-castle',
    title: 'Osaka Castle Plum Blossom Picnic',
    city: 'Osaka',
    neighborhood: 'Chūō-ku',
    date: '2026-03-19',
    startTime: '13:00',
    durationMin: 120,
    description:
      'The last plum blossoms ring the moat while the keep rises white and gold behind them. We bring a spread from the local market and claim a spot on the grass for a slow afternoon.',
    tags: ['Nature', 'Festivals'],
    matchReason: 'Because you chose Festivals',
    host: { name: 'Daichi Yamamoto', avatarUrl: '', verified: true },
    saveCount: 933,
    shareCount: 145,
    videoUrl: null,
    posterUrl: p('osaka-castle'),
    lat: 34.6873,
    lng: 135.5262,
    ageAccess: 'All ages',
  },
]

export function getExperience(id: string) {
  return EXPERIENCES.find((e) => e.id === id)
}
