/**
 * Bridge: engine `ExperienceCard` -> the v0 app's `Experience` type.
 *
 *   cp docs/roam-client.ts lib/roam.ts
 *   cp docs/v0-adapter.ts  lib/engine.ts
 *   pnpm add @supabase/supabase-js
 *
 * Then in the screen that currently reads presets from lib/data.ts:
 *
 *   import { loadFeed } from '@/lib/engine'
 *   const experiences = await loadFeed()      // Experience[], ranked
 *
 * Nothing else changes. Same shape the presets had, same components, but
 * every row is real and `matchReason` is the engine's own explanation for
 * why that card ranked for this traveller.
 */

import { continueAsGuest, getFeed, getSessionState, type ExperienceCard } from './roam'
import type { Category, City, Experience } from './types'

/**
 * Engine categories are lowercase slugs; the app's Category union is
 * capitalised and has entries the engine has no equivalent for. Anything
 * unmapped is dropped rather than coerced — a wrong tag on a card is worse
 * than a missing one.
 */
const CATEGORY: Record<string, Category> = {
  food: 'Food', nightlife: 'Nightlife', art: 'Art', anime: 'Anime',
  music: 'Music', nature: 'Nature', shopping: 'Shopping', festival: 'Festivals',
  wellness: 'Wellness', traditional: 'Traditional', market: 'Local Markets',
  hiking: 'Hiking', beach: 'Beaches', photography: 'Photography',
  architecture: 'Architecture', history: 'History', coffee: 'Coffee',
  design: 'Design', fashion: 'Fashion', film: 'Film', sport: 'Sports',
}

const toTags = (card: ExperienceCard): Category[] => {
  const seen = new Set<Category>()
  for (const slug of [card.category, ...card.tags]) {
    const mapped = CATEGORY[slug]
    if (mapped) seen.add(mapped)
  }
  return [...seen]
}

/** The engine gates minors on tags, not on a rating; surface the same fact. */
const ageAccess = (card: ExperienceCard): string =>
  card.tags.some((t) => ['alcohol', 'nightlife', 'bar', 'club', 'gambling', 'sake', 'izakaya'].includes(t))
  || card.category === 'nightlife'
    ? '20+'
    : 'All ages'

export function toExperience(card: ExperienceCard, fallbackDate: string): Experience {
  // `starts_at` is null for always-available attractions. The app wants every
  // card on a day, so fall back to the date passed in rather than inventing one.
  const when = card.starts_at ? new Date(card.starts_at) : null
  return {
    id: card.experience_id,
    title: card.name,
    city: card.city as City,
    neighborhood: card.neighborhood ?? card.city,
    date: when ? when.toISOString().slice(0, 10) : fallbackDate,
    startTime: when ? when.toISOString().slice(11, 16) : '',
    durationMin: card.duration_min ?? 120,
    description: card.short_description,
    tags: toTags(card),
    // The whole point of the engine. reasons[0] is generated by the same SQL
    // expression that produced the score, so it cannot drift from the ranking.
    matchReason: card.reasons[0] ?? '',
    host: {
      name: card.host_name ?? 'Local host',
      avatarUrl: '',
      verified: card.host_verified,
    },
    saveCount: card.save_count,
    shareCount: card.share_count,
    // Pointers only — never a rehosted file. Placeholder rows have no source.
    videoUrl: card.media_kind === 'tiktok' || card.media_kind === 'instagram'
      ? card.media_source_url
      : null,
    posterUrl: card.media_thumbnail_url ?? '',
    lat: card.lat,
    lng: card.lng,
    ageAccess: ageAccess(card),
  }
}

/**
 * One call for the deck. Signs the visitor in anonymously if they have no
 * session — no signup wall, and the profile it mints is what RLS scopes
 * every later save and itinerary to.
 */
export async function loadFeed(fallbackDate = '2026-03-14'): Promise<Experience[]> {
  const state = await getSessionState().catch(() => null)
  if (!state?.signed_in) await continueAsGuest()
  const cards = await getFeed({ limit: 40 })
  return cards.map((c) => toExperience(c, fallbackDate))
}
